tab_info <- tabItem(tabName = "info",
        fluidRow(
          box(title = "Quick info",
              title_side = "top left",
              value_box("Films",
                        nrow(movies),
                        color = "blue",
                        size = "huge"),
              value_box("In Color",
                        length(which(movies$color == "Color")),
                        color = "teal",
                        size = "huge"),
              value_box("Directors", length(unique(movies$director_name)),
                        color = "teal",
                        size = "huge"),
              value_box("Countries", length(unique(movies$country)),
                        color = "teal",
                        size = "huge")
          ),
          column(width = 7,
                 box(title = "Years",
                     value_box("From year", min(movies$title_year),
                               color = "teal",
                               size = "tiny"),
                     value_box("To year", max(movies$title_year),
                               color = "teal",
                               size = "tiny")),
                 box(title = "Rankings",
                     value_box("Best film overall",
                               movies$movie_title[(which.max(movies$imdb_score))],
                               color = "teal",
                               size = "tiny"),
                     value_box("Worst film overall",
                               movies$movie_title[(which.min(movies$imdb_score))],
                               color = "teal",
                               size = "tiny"),
                     value_box("Highest gross",
                               movies$movie_title[(which.max(movies$gross))],
                               color = "olive",
                               size = "tiny")
                 )
          )
        )
)